### ISSUE TITLE
License conflicts 

### ISSUE THREAD

**Issue by ghost** [Asari-DataScience/Programming-work-collection#1]
ルートディレクトリではGPL3.0が設定されていますが、個人でライセンスが設定可能であれば、このファイルは消すべきではないのでしょうか。
文が変な気がしますが、伝われば幸いです。

By google translate:
GPL3.0 is set in the root directory, but if the license can be set individually, shouldn't this file be deleted?
I feel like the sentence is strange, but I would appreciate it if you could convey it.

**Comment by Asari-DataScience** [comment]
すみません リポジトリを作成したあとになんか言われるやつ（Add READMEとAdd LICENCE）をクリックしたのを忘れてました
ただそれだとGitHubがLICENCEとして認識しないので「個人の設定したものに従う」みたいな内容にしておきます

2022年12月5日(月) 18:25 IAX86 ***@***.***>:

**Comment by Asari-DataScience** [comment]
追記：LICENCEファイルがルートディレクトリにあるとライセンス違反防止になるため、ルートのあれは残すべきだと思います

**Comment by ghost** [comment]
ありがとうございます。
ファイルと内容の件、了解しました。
